# Generated by Django 4.1.3 on 2022-11-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=122)),
                ('Fname', models.CharField(max_length=122)),
                ('Lname', models.CharField(max_length=122)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.IntegerField()),
                ('CPassword', models.IntegerField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
