# Generated by Django 4.1.3 on 2022-11-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearBy_Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=122)),
                ('department', models.CharField(max_length=122)),
                ('location', models.CharField(max_length=122)),
            ],
        ),
    ]
