# Generated by Django 4.1.3 on 2022-11-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_nearby_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearby_doctor',
            name='working_H',
            field=models.CharField(default='', max_length=122),
            preserve_default=False,
        ),
    ]
