# Generated by Django 4.1.3 on 2022-11-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_nearby_doctor_working_h'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se_dept', models.CharField(max_length=122)),
                ('se_doc', models.CharField(max_length=122)),
                ('patient_name', models.CharField(max_length=122)),
                ('patient_phone', models.IntegerField()),
                ('patient_email', models.EmailField(max_length=254)),
                ('calendar', models.DateField()),
            ],
        ),
    ]
