# Generated by Django 4.1 on 2022-11-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearby_doctor',
            name='brife',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
