# Generated by Django 4.1.3 on 2022-12-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reviews', models.CharField(max_length=200)),
                ('time', models.TimeField()),
            ],
        ),
    ]
