# Generated by Django 4.1 on 2022-11-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_nearby_doctor_brife'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearby_doctor',
            name='clinicloc',
            field=models.CharField(default=' ', max_length=122),
            preserve_default=False,
        ),
    ]
