# Generated by Django 4.1 on 2022-11-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_nearby_doctor_clinicloc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nearby_doctor',
            name='brife',
        ),
        migrations.RemoveField(
            model_name='nearby_doctor',
            name='clinicloc',
        ),
    ]
