# Generated by Django 4.1 on 2022-11-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_nearby_doctor_nw_pat_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearby_doctor',
            name='ret_pat_fee',
            field=models.CharField(default='100', max_length=122),
            preserve_default=False,
        ),
    ]
