# Generated by Django 4.1 on 2022-11-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_nearby_doctor_ret_pat_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearby_doctor',
            name='lag_spoken',
            field=models.CharField(default='eng', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nearby_doctor',
            name='repo_fee',
            field=models.CharField(default='100', max_length=122),
            preserve_default=False,
        ),
    ]
