# Generated by Django 4.1 on 2022-12-02 12:30

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_nearby_doctor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_image', models.ImageField(blank=True, null=True, upload_to=home.models.filepath)),
                ('pat_name', models.CharField(max_length=122)),
                ('pat_age', models.CharField(max_length=122)),
                ('pat_location', models.CharField(max_length=122)),
                ('pat_lag_spoken', models.CharField(max_length=122)),
                ('pat_occu', models.CharField(max_length=122)),
            ],
        ),
        migrations.AlterField(
            model_name='nearby_doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.filepath),
        ),
    ]
