# Generated by Django 4.1 on 2022-12-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_merge_0009_rating_0020_health_bllod_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nearby_doctor',
            old_name='image',
            new_name='doc_image',
        ),
    ]
