# Generated by Django 4.1.4 on 2022-12-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
