# Generated by Django 4.1 on 2022-12-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_image_nearby_doctor_doc_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewers',
            name='ip',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewers',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewers',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
