# Generated by Django 4.1 on 2022-12-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_reviewers_ip_reviewers_rating_reviewers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewers',
            name='rating',
            field=models.FloatField(),
        ),
    ]
