# Generated by Django 4.1 on 2022-12-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_reviewers_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewers',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='reviewers',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='reviewers',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='reviewers',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reviewers',
            name='time',
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('review', models.TextField(blank=True, max_length=500)),
                ('rating', models.FloatField()),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.nearby_doctor')),
                ('pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patient')),
            ],
        ),
    ]
