# Generated by Django 4.1 on 2023-01-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_patientlist'),
        ('home', '0025_remove_reviewers_ip_remove_reviewers_rating_and_more'),
    ]

    operations = [
    ]
